version: "3.7"
services:
    # image project
    app:
        build: 
            args: 
                user: joao
                uid: 1000
            context: ./
            dockerfile: Dockerfile
        image: laravel-app
        restart: unless-stopped
        working_dir: /var/www/
        volumes:
            - ./:/var/www
        depends_on: 
            - redis
            - queue
        networks: 
            - pic-test
    
    # nginx
    nginx:
        image: nginx:alpine
        restart: unless-stopped
        ports: 
            - 80:80
        volumes: 
            - ./:/var/www
            - ./docker/nginx/:/etc/nginx/conf.d/
        networks: 
            - pic-test

    # db mysql
    mysql:
        image: mysql:5.7.22
        restart: unless-stopped
        ports: 
            - 3308:3306
        environment: 
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
            MYSQL_PASSWORD: ${DB_PASSWORD}
            MYSQL_USER: ${DB_USERNAME}
            MYSQL_ROOT_HOST: '%'
        volumes: 
            - ./.docker/mysql/dbdata:/var/lib/mysql
        networks: 
            - pic-test

    # phpmyadmin
    adminphp:
        container_name: phpmyadmin
        image: phpmyadmin/phpmyadmin
        restart: unless-stopped
        links:
        - "mysql:db"
        ports:
        - "3382:80"
        networks:
        - pic-test

    # queue
    queue:
        build: 
            args: 
                user: joao
                uid: 1000
            context: ./
            dockerfile: Dockerfile
        restart: unless-stopped
        command: "php artisan queue:work"
        volumes: 
            - ./:/var/www
        depends_on: 
            - redis
        networks: 
            - pic-test

    # redis
    redis:
        image: redis:latest
        networks: 
            - pic-test

networks: 
    pic-test:
        driver: bridge